### ISSUE TITLE
Suggestion: RUDE for DOS?

### ISSUE THREAD

**Issue by OpenRift412** [drfrag666/RUDE#10]
More just an idea for consideration. I think bringing a more powerful limit-removing port like RUDE to DOS would honestly be a cool idea as well as open up more possibilities for playing in Doom's native OS. So far the only alternative we have currently for playing in DOS is Doom-plus/Doom2-plus, which, while great, do have problems with more complex limit-removing WADs like Deathless or Scythe 2, as those require more limits to be raised.

**Comment by drfrag666** [comment]
Sorry, that's not possible. It's like asking for a Chocolate Doom for DOS. But there are other limit-removing ports for DOS AFAIK.
