### ISSUE TITLE
Super Shotgun Firing Animation Bug Not Present

### ISSUE THREAD

**Issue by OpenRift412** [drfrag666/RUDE#12]
Something I notice with RUDE is that the firing frame bug for the SSG as seen in vanilla is not present in RUDE. Is this intentional or was this an oversight when porting features from Crispy?

**Comment by drfrag666** [comment]
Of course it's intentional. It's just a silly bug and the fix doesn't break demos. I usually fix those and game-breaking bugs. A different thing is using MBF code to fix rendering glitches.
