### ISSUE TITLE
Not showing error window on crash

### ISSUE THREAD

**Issue by OpenRift412** [drfrag666/RUDE#13]
I'm not sure if this was intentional or not, but for some reason RUDE doesn't spit out any error windows when the game crashes for whatever reason. I've tested it in the same scenarios with Chocolate and it normally gives you a proper error message. Is there a setting I toggled that disables this?

**Comment by drfrag666** [comment]
There's no crash report window in Chocolate Doom, crashes are silent AFAIK. Do you mean those popups when limits are exceeded? RUDE is limit removing, it doesn't abort but those messages (and others) are sent to the console instead. When do you get a crash?

**Comment by OpenRift412** [comment]
> There's no crash report window in Chocolate Doom, crashes are silent AFAIK. Do you mean those popups when limits are exceeded? RUDE is limit removing, it doesn't abort but those messages (and others) are sent to the console instead. When do you get a crash?

Chocolate Doom does show a crash report window, I'm mostly talking about stuff like:
`W_CacheLumpNum: %i >= numlumps`
`R_FlatNumForName: %s not found`

That sort of thing.

**Comment by drfrag666** [comment]
That's not a crash, like i've said those error messages are shown in the console instead.

**Comment by OpenRift412** [comment]
> That's not a crash, like i've said those error messages are shown in the console instead.

Well is there a way to enable a console log? Because the console window closes before I can even see the issue.

**Comment by drfrag666** [comment]
It should close when you close the enddoom screen. May be it's an actual crash then it would be a bug.
You can see the messages too running from the command prompt.

**Comment by OpenRift412** [comment]
> It should close when you close the enddoom screen. May be it's an actual crash then it would be a bug.
> You can see the messages too running from the command prompt.

Well I'm talking about it closing on launch.
