### ISSUE TITLE
Suggestion: Change repository name

### ISSUE THREAD

**Issue by fragglet** [drfrag666/RUDE#7]
Great to see another fork but it's a bit confusing that this is still named `chocolate-doom` :)

**Comment by drfrag666** [comment]
RUDE is not new but i've been working on it intermittenty and recently merged with your master.
That said i'm still convinced that the port is very cool, there were still some problems with backpacks and now i've added the possibility to exchange stimpacks. The new skill setting is great fun in coop with fake splitscreen and i still want to create a game of extreme doom online and join the master server. :) About 8 player support i'm still not sure of what to do.
That was the default name and i wasn't given the option to change it AFAIR. Most "forks" keep the same name. Then i forgot that it could be changed. Done.

**Comment by fragglet** [comment]
Thanks!
