### ISSUE TITLE
Center UI elements in widescreen

### ISSUE THREAD

**Issue by drfrag666** [drfrag666/RUDE#8]
@JNechaevsky
Someone has complained about widescreen "not working" and said "the HUD, title screen, text, and the menu are shifted to the left".
 Does it really look that bad? I know everyone is adjusting everything to be centered.
 > With the adjustment i need to fill with black the other side (or stone graphics) besides centering everything including the status bar numbers and if i center the automap the markers.

**Comment by JNechaevsky** [comment]
@drfrag666, sadly, yes, it's a paint for the eyes. :( I would like to recomment centering, but now I also know, that "DELTA" can't be used as macro.

**Comment by drfrag666** [comment]
I didn't feel like doing it but now i guess i'll have to. Why not?

**Comment by drfrag666** [comment]
Well if you don't want to add conditionals everywhere it's better to use another global variable.

**Comment by drfrag666** [comment]
And it's done in commits: https://github.com/drfrag666/RUDE/commit/061293f4fb3f17c0437822a1d6b6549492d57880 and https://github.com/drfrag666/RUDE/commit/e8ea3a954284d691e2f88bdc07bc48f1a0e28714
Mostly taken from Crispy, the key is to make the adjustment inside V_DrawPach. You could do the same i did here with WIDEWIDTH_DELTA but with SCREENWIDTH to get one executable, as i said earlier.
