### ISSUE TITLE
Suggestion: Toggle to Hide 'Unholy Massacre' Title Graphic

### ISSUE THREAD

**Issue by OpenRift412** [drfrag666/RUDE#9]
Hi, this is a nice port ya got here, definitely prefer this over Crispy Doom imo. Just one thing. I think something that would be nice to have is the ability to toggle the appearance of 'Unholy Massacre' in the difficulty select screen. I guess I'm just being pedantic, but having the ability to do that I think would help create the proper "vanilla-plus" experience a lot of people (or maybe just me) are looking for.

**Comment by drfrag666** [comment]
It's doable. Sometimes it looks a bit out of place with custom menus, but i would only add another command line parameter to remove it.

**Comment by drfrag666** [comment]
Added, it was very simple after all. I will release another test later or tomorrow with support for the Unity iwads.
